<a href="https://colab.research.google.com/github/isababale/My-Documents-/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Autograd**

Autograd is PyTorch’s automatic differentiation engine.
It automatically calculates gradients (derivatives) for you — which are essential for training machine learning models using gradient descent.

In [2]:
import torch
cuda0=torch.device('cuda:0')

In [3]:
x=torch.tensor([5],dtype=torch.float,requires_grad=True)
y=torch.tensor([6],dtype=torch.float,requires_grad=True)
print(x)
print(y)

tensor([5.], requires_grad=True)
tensor([6.], requires_grad=True)


In [4]:
# defining the function
z=((x**2)*y)+(x*y)
print(z)

tensor([180.], grad_fn=<AddBackward0>)


In [5]:
# usng autograd
# autograd to be applied on scalar
total =torch.sum(z)
print(total)


tensor(180., grad_fn=<SumBackward0>)


In [6]:
total.backward()

In [7]:
print(x.grad)

tensor([66.])


In [8]:
print(y.grad)

tensor([30.])


In [9]:
x=torch.randn(10,requires_grad=True)
print(x)

tensor([ 1.2251,  0.3490,  0.5034, -0.0805, -0.5455,  1.0165, -0.2344, -0.8856,
         0.2955, -0.6256], requires_grad=True)


## **Building intuition on Autograd**

In [10]:
x=torch.randn(10,device=cuda0)
x

tensor([-0.0258, -1.3162, -1.4225,  1.0516,  0.9411, -0.0402, -0.2711, -0.9333,
         0.9416,  1.3084], device='cuda:0')

In [11]:
# function
y=1.8*x +32 # wx+b
y  # pred

tensor([31.9535, 29.6308, 29.4395, 33.8929, 33.6940, 31.9276, 31.5120, 30.3201,
        33.6949, 34.3550], device='cuda:0')

In [12]:
w=torch.ones(1,requires_grad=True,device=cuda0)
b=torch.ones(1,requires_grad=True,device=cuda0)
y_hat=w*x+b # predicted values of the output

In [13]:
# loss function
loss=torch.sum((y_hat-y)**2)


In [14]:
loss

tensor(9627.5312, device='cuda:0', grad_fn=<SumBackward0>)

In [15]:
loss.backward()

In [16]:
print(w.grad,b.grad)

tensor([-29.3486], device='cuda:0') tensor([-620.3737], device='cuda:0')


## **Implementing autograd**

In [19]:
x= torch.randint(-100,100,(100,), dtype=torch.float32, device=cuda0)
y=1.8*x + 32
w=torch.ones(1,requires_grad=True,device=cuda0)
b=torch.ones(1,requires_grad=True,device=cuda0)
y_hat=w*x+b
epochs=100000
lr=0.000001

for i in range(epochs):
  y_hat=w*x+b
  loss=torch.sum((y_hat-y)**2)
  loss.backward()
  # w-=lr*w.grad -- this will be considered as relationship
  with torch.no_grad(): # this will swith off gradiends
    w-=lr*w.grad
    b-=lr*b.grad

    # setting the gradients to be zero
    w.grad.zero_()
    b.grad.zero_()

y_hat=w*x+b
print(w.item(),b.item())


1.8000075817108154 31.99519920349121
